#====== Aliases
#-- General
shopt -s expand_aliases
alias l='ls -l'
alias ll='ls -Al'
alias vim='$(if type nvim &> /dev/null; then echo nvim; else echo vim; fi)'
alias ..='cd ..'
alias tree='tree -C'
alias trls='tree -C | less -R'
alias re='source ~/.bashrc'
alias h='hostname'
alias p='pwd;pwd -P'
alias ks='kyrat'

#-- Project Related
