theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
undercurl = true
rulers = [79]
popup-border = "all"

[editor.statusline]
right = ["diagnostics", "selections", "total-line-numbers", "position", "version-control"]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.insert]
j = { k = ["normal_mode", ":w"] }

[keys.normal]
C-r = [":config-open", ":config-reload"]
C-y = [":clipboard-yank"]
A-l = [":open ~/.config/helix/languages.toml"]

[keys.select]
C-y = [":clipboard-yank"]
